const constans = {
  LOGIN_PENDING: 'LOGIN_PENDING',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_ERROR: 'LOGIN_ERROR',
  SIGNUP_PENDING: 'LOGIN_PENDING',
  SIGNUP_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  SIGNUP_ERROR: 'LOGIN_ERROR'
};
export default constans;
